version: "3.7"

services:
  db:
    container_name: to-done-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  maildev:
    image: maildev/maildev
    ports:
      - '8080:1080'
      - '8025:1025'
    environment:
      MAILDEV_INCOMING_USER: ${EMAIL_SERVER_USER}
      MAILDEV_INCOMING_PASS: ${EMAIL_SERVER_PASSWORD}
